travis:
  secure:
    BINSTAR_TOKEN: FHY+PYuuG1+zhT+ND9cDgaRMa8W6WtNbcu5X215u5lC/O+ruT8gBIBLtMveAgzAFITO9obhNKqzXi8Rmz48Juc4ymSqe1HF5lQDvVVPUWGYomq8EhqYoDotOX8rp80CSjBhQ+ZixhKd3XIEqKnZh+OO5MGrCpm9cAnASg+8TPKmA1Pq+/pHV0WZkO48Eb0Q2ozBNQlJiTPoPk4gchnyC0Gkd6VHT3KYk8JhkIQJDgmGtn8fzYImDehmGziA5L8pq4yBug/TOWmivrFzIFHFfr1OwsAwrCArvyrTbsHKtq8Nmgy/wPfNsVQxFoMnmJ4Y4JwirnnbAqxSwyAJruXirQmK97VTU3FDhDE6BL3YeTPyYBrtRz06ltmoVubtaFrf7n9w8bHWV3XlL+6Mzq2Q6TDc3ASK6ZKQb/0bhzChx+0ZSSuCI4crA4nL+gI9NzbpgCeQsee6pJdsbqT8Ng/KIG3CPm9EZa5Iq6s6opj9obD65qpV1QpvRikWPGKl+ebP/9miQ03TiAtPHsbEBF/LzwsuyaNEoNCHJ6+FtpT20TNGBm+wvxdJ8iJ7+vdl1gmpl1jKyrHNEw+0P00TD9PAf+AvNVne4tnJb5LZVqpriFBtNsVpDEgHxiNv288L9m922842d3s6wgL4jSNiIksu/k1GHRyYri7PcwfgjEix/0rg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
