travis:
  secure:
    BINSTAR_TOKEN: tp8WEnBUBRdFS853HrlKbCq4z4aLYILIardhguGBit2qYLRs3bLDAS4XvqeVcWWm5QoaC75FgAUFdLTJ/jbjJlGSrl+Y3rReRXPvwNwxr/pdnCSupjwIZVvJ7t6KsGshymRZA06TsYw7TzN0wFgsa8gnenLvpjgQvCP2vJ+yXez4K7Cu4Id4wtN1614tqZw5K+IfoQfZV+RnZRuqlWl5Xnw8s9P6eh46PlAW2vHlkQgti3eQvulcnqWQTtxJnxDuAjuI93z8JCodFnCgYjQ5JGFOPXAumEmAphdnhu8vAlBRUSK3Xly2l8HY+7TCbd/xKHOdie5cnBz7EEV+FR1VadjVL8tfXFVw+ShRD/ZqT81Y38ZR/ZPMyMRsdf7Bpxxmf9IQ+BNz59S/syaI1hWJXaMoPQVaLzJLgbNt83XCa7gR8ZVDFbqeD1DmFAfvuN8LqQE8pbGiE6q/3kzU5xnuV19Y1kbGzHPcVMYs7cIklkF+FgKhziROK5OW2zfz+LQnrYmVuJOegX3DKXkbs2CyIM1JTaSXqCcy5vypKjjFQjfjcFkA3PTgzpSo5UQq9xCrULZPk0+X7cLonwZXYrIHaRZF8tPPQ5tBdwfM/tdgSOKBOifnsbfU0hMU2bCH1l3Oa5MVO3gEalut1u12K69t1mhnHQsPhXpUpzF7LeWGGxk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
