travis:
  secure:
    BINSTAR_TOKEN: Ma7YRIXPVrEEL4ewyFt/cgtW8mmfczmUWz55zwjsrC4vIg7ETzA0wsZ+tHkBI4zIYC7cG2JjSsI7HCzehwCxdjXgOElP14MDrFTEh5kxllZn+cg0fruycYES/O+kt2v/FxAtZZqfCZ3cOgJDZaJT0I0kLEfZFcDkBVW2cgoamofxXjsxxgj31DGBec6B2Le+Sr5CZD9xvNfLAj49jJE/9ymwKCadqD8Tvk3uV2fjuLe+Dh3nNkIQwjXa/LuTGSPXPXynp7/eHTVmZiOpxDB7l80Z6Bl4vbQ0tzRFLvAl4AlUB1Iw1nMEOv/KTmqRQWRk3Z7xkfr9NtaUNWlEW4/z5drL5jdTnw7x4IS+DV1PAGogTNqhU9k/0yHMpn/U2nS0oCaq+UL1P0qe78hkQ8N/D5d0e5oh0gtHvJhVMbCwtLsQURPkvoQ/B/Mcf/sCh+9i+Uzz/aH7BbrSVXLfJ4xFUNMxgnb0MDUh6+SKNU2VRUOY058O2CA1ZGLXcf6gJ3bM9UOUDC1yQBLjuL5XkMBbk67LRpwFIrpHKj/4BOCAMEQWkA2tpa1Lb7vyjgRXAnx3dylM3Kx+RIkb6nz69yE1hJct6Y6tc1FMxo6A2NTvRqZ4IZ7/lTM4r2IXnYk3hW6AeFTmr7N89dbAQTuc0VuRgo9t9bNQYsMj67/xcfCfubs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
